In [2]:
import pandas as pd
import nfl_data_py as nfl 
import os

In [3]:
# Import draft pics from 2000-2023

draft_df = pd.read_csv('Resources/draft_2000-2023.csv')
draft_df.head()

,draft_year,rnd,pick,tm,player,pos,g,search_key,id,year_signed,signing_tm,value,value_norm,gtd,gtd_norm
0,2000,1.0,1.0,CLE,Courtney Brown,DE,61.0,"Courtney Brown, DE",0,2000.0,Browns,44939436.0,0.722824,10880250.0,0.175002
1,2000,1.0,1.0,CLE,Courtney Brown,DE,61.0,"Courtney Brown, DE",0,2004.0,Browns,14700000.0,0.182423,2000000.0,0.024819
2,2000,1.0,1.0,CLE,Courtney Brown,DE,61.0,"Courtney Brown, DE",0,2003.0,Browns,20500000.0,0.273308,1000000.0,0.013332
3,2000,1.0,1.0,CLE,Courtney Brown,DE,61.0,"Courtney Brown, DE",0,2005.0,Broncos,18800000.0,0.219883,1260000.0,0.014737
4,2000,1.0,1.0,CLE,Courtney Brown,DE,61.0,"Courtney Brown, DE",0,2006.0,Broncos,5400000.0,0.052941,1055000.0,0.010343

In [9]:
# Condense the drafts to 2016-2019 and keeping only the first round picks

draft_16_19= draft_df[(draft_df['draft_year'] >= 2016) & 
                                   (draft_df['draft_year'] <= 2019) & 
                                   (draft_df['rnd'] == 1.0)].reset_index(drop=True)
draft_16_19.head()

,draft_year,rnd,pick,tm,player,pos,g,search_key,id,year_signed,signing_tm,value,value_norm,gtd,gtd_norm
0,2016,1.0,1.0,LAR,Jared Goff,QB,100.0,"Jared Goff, QB",3658,2019.0,DET/LAR,134000000.0,0.712009,110042682.0,0.584711
1,2016,1.0,1.0,LAR,Jared Goff,QB,100.0,"Jared Goff, QB",3658,2016.0,Rams,27937672.0,0.179930,27937672.0,0.179930
2,2016,1.0,2.0,PHI,Carson Wentz,QB,93.0,"Carson Wentz, QB",3659,2019.0,IND/PHI/WAS,128000000.0,0.680128,107870683.0,0.573170
3,2016,1.0,2.0,PHI,Carson Wentz,QB,93.0,"Carson Wentz, QB",3659,2016.0,Eagles,26676338.0,0.171806,26676338.0,0.171806
4,2016,1.0,3.0,SDG,Joey Bosa,DE,84.0,"Joey Bosa, DE",3660,2020.0,Chargers,135000000.0,0.681130,102000000.0,0.514632

In [5]:
# Import data from 'nfl_data_py' library

import_data = nfl.import_draft_picks(range(2016, 2020))
nfl_import = pd.DataFrame(import_data)

# Save it as a new csv file
csv_path = os.path.join('Resources', 'from_nfl_data.csv')
nfl_import.to_csv(csv_path, index=False)

In [6]:
# Read the "from_nfl_data" file

library_draft = pd.read_csv('Resources/from_nfl_data.csv')
library_draft.head()

,season,round,pick,team,gsis_id,pfr_player_id,cfb_player_id,pfr_player_name,hof,position,...,pass_ints,rush_atts,rush_yards,rush_tds,receptions,rec_yards,rec_tds,def_solo_tackles,def_ints,def_sacks
0,2016,1,1,LAR,00-0033106,GoffJa00,jared-goff-1,Jared Goff,False,QB,...,82.0,241.0,495.0,12.0,1.0,5.0,0.0,2.0,NaN,NaN
1,2016,1,2,PHI,00-0032950,WentCa00,carson-wentz-1,Carson Wentz,False,QB,...,67.0,354.0,1418.0,11.0,2.0,11.0,0.0,1.0,NaN,NaN
2,2016,1,3,SDG,00-0033156,BosaJo00,joey-bosa-1,Joey Bosa,False,DE,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,235.0,NaN,67.0
3,2016,1,4,DAL,00-0033045,ElliEz00,ezekiel-elliott-1,Ezekiel Elliott,False,RB,...,0.0,2065.0,8904.0,71.0,356.0,2649.0,14.0,2.0,NaN,NaN
4,2016,1,5,JAX,00-0033055,RamsJa00,jalen-ramsey-1,Jalen Ramsey,False,CB,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,393.0,22.0,2.0

In [11]:
columns_to_keep = ['season', 'round', 'team', 'pfr_player_name', 'category', 'college', \
                   'age', 'allpro', 'seasons_started', 'dr_av', 'games', 'pass_yards', \
                    'pass_tds', 'rush_yards', 'rush_tds', 'receptions', 'rec_yards', 'def_ints', \
                        'def_sacks']

players_stats = library_draft[columns_to_keep]
players_stats.head()

,season,round,team,pfr_player_name,category,college,age,allpro,seasons_started,dr_av,games,pass_yards,pass_tds,rush_yards,rush_tds,receptions,rec_yards,def_ints,def_sacks
0,2016,1,LAR,Jared Goff,QB,California,21.0,0,6,47.0,117.0,30429.0,185.0,495.0,12.0,1.0,5.0,NaN,NaN
1,2016,1,PHI,Carson Wentz,QB,North Dakota St.,23.0,0,6,43.0,95.0,22292.0,153.0,1418.0,11.0,2.0,11.0,NaN,NaN
2,2016,1,SDG,Joey Bosa,DL,Ohio St.,21.0,0,6,51.0,93.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,67.0
3,2016,1,DAL,Ezekiel Elliott,RB,Ohio St.,21.0,1,7,64.0,120.0,4.0,0.0,8904.0,71.0,356.0,2649.0,NaN,NaN
4,2016,1,JAX,Jalen Ramsey,DB,Florida St.,21.0,3,7,29.0,118.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,2.0